# Site settings
title: "ZhangTP's Resume"
description: "A resume of ZhangTP."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tianping Zhang"
resume_title:                   "There is only one definition of success - to be able to spend your life in your own way"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ztp18@mails.tsinghua.edu.cn"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "13606030330"
resume_contact_address:         "Tsinghua University"

resume_header_contact_info:     "Tsinghua University • 13606030330 • fenghaozhe1996@gmail.com"
display_header_contact_info:    "True"

resume_header_intro: "<p>I am studying for a Ph.D. in the ADL Group of IIIS at Tsinghua University. I received my BS degree in Mathematics Statistics from Zhejiang University. My research interest includes machine learning and its applications in finance.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        False
resume_section_skills:          False
resume_section_recognition:     False
resume_section_links:           false
resume_section_associations:    False
resume_section_interests:       False
resume_section_publications:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/FengHZ"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://www.zhihu.com/people/feng-hao-zhe-66/activities"
  resume_medium_url:            "http://Fenghz.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
